### ISSUE TITLE
CI/CD to Automate Docker Layers Generation, PreCompiled toolchain and executables 

### ISSUE THREAD

**Issue by fjtrujy** [pspdev/pspdev-docker#12]
Hello,

I'm just writing here because @ooPo recommended to contact you and more concretely @dbeef, and I was thinking that this repo was the most appropriate to explain this.

We have recently integrated a whole and complex CI/CD in the `ps2dev` GitHub group using `GitHub Actions` and `DockerHub` we don't longer need to have `TravisCI` in place.

Now we have several repositories that are generating docker layers and/or artifacts, and the most interesting thing, once they finish, they dispatch notifications to trigger compilation in other repositories, to generate more docker layers and artifacts.

In the end, `ps2dev` repositories and `pspdev` repositories have similar "architecture", so I suppose that we can basically copy & paste the implementation that we did.

Giving a quick overview.

- We're generating 5 different dockers layers, giving the last one, the most useful for Developers that want to use dockers to assure that their projects are stable.
- We are generating a precompile toolchain (for macOS and Ubuntu 64) where lazy developers just can do there and grab it instead to compile it in their machine.
- We are generating several executables (.elf), like examples around the different repos or tools it-self.

Everything is done in a maximum of **15 minutes in the worst scenario**.
Some useful links.

- Here you can see the different dockers layers (if you see there are extremely small)
https://hub.docker.com/u/ps2dev/

- Precompiled complete toolchains
https://github.com/ps2dev/ps2dev/actions/runs/108959675

- Some compiled examples
https://github.com/ps2dev/ps2sdk/actions/runs/108501085
https://github.com/ps2dev/gskit/actions/runs/108957621

So, just tell me if you're interested. @ooPo have my contact so we can start a conversation as you wish!

Thanks

**Comment by sharkwouter** [comment]
I would say this would be amazing to have. We would need a maintainer to create the pspdev organization on the Dockerhub for it.

Providing binaries for Mac and perhaps also Windows would be great. I'm not too big a fan of providing a prebuild version for Ubuntu, though, since people on other distributions will probably end up using it too.

Assuming others think this is a great idea as well, we would need to know which steps we'd need to take to be able to implement this. Could you provide a short list?

**Comment by fjtrujy** [comment]
Good to ear this!

So, first of all, I have the `pspdev` organization created by myself in DockerHub.

The reason why we have the pre-compiled toolchain, even for Ubuntu, is because this is for free, and anyway you should check that the toolchain is compiling for ubuntu.... so reached that point doesn't make sense to don't offer it.

Then the steps to follow, just to start **is to identify the different docker layers that you want to create and how the repositories are connected themselves**.

As I said before, the repository in `ps2dev` and `pspdev` are quite similar, but we have done some "improvements" from our point of view.

The most radical changes have been to reduce the "scope" of `ps2toolchain` to just compile, binutils, gcc and newlib (probably you also need to include gdb) and then additionally we have created a new repo called `ps2dev` which offer the whole development environment, either as docker file or precompiled toolchain.

Here you have a copy and paste about the whole CI/CD flow we have done in the `ps2dev`. Please take a look and see how this adjusts to the `pspdev` group.

![2020-05-15](https://user-images.githubusercontent.com/10010409/82449246-36575680-9aab-11ea-8d41-9af515fa5cf4.png)

```
The main objectives are basically 4:

Assure that the changes keep the compilation successful.
Generation of artifacts. They could be PS2 Executables (.elf), local machine content
Generation of several docker layers. This is useful either for compiling some repos inside of ps2dev or for external application as OPL, RetroArch or uLaunch
A change in a repo could dispatch an action to associated repos to trigger their CI/CD and update Docker images.

The repos that are involved in the implemented CI/CD are:

ps2toolchain
The scope of this repository now has been reduced, this is no longer the repo that you need to clone if you want to install ps2 environment in your local machine if you wanna do this your repo now, is ps2dev.
The ps2toolchain is just now, compiling binutils, gcc and newlib.
This repo generate:
1st docker layer, named ps2dev/ps2toolchain:latest and it is composed by:
alpine:latest + ps2toolchain
Once that the docker image has been build and uploaded to DockerHub, a dispatch action is being sent to ps2sdk repo.

ps2sdk
This repo uses the docker image ps2dev/ps2toolchain:latest as reference for the CI/CD process. The CI/CD in this case just check that the compilation works as expected.
This repo generate:
2nd docker layer, named ps2dev/ps2sdk:latest and it is composed by:
alpine:latest + ps2toolchain + ps2sdk
Once that the docker image has been build and uploaded to DockerHub, a dispatch action is being sent to gsKit and ps2-packer repos.

ps2-packer
This repo uses the docker image ps2dev/ps2sdk:latest as reference for the CI/CD process. The CI/CD in this case just check that the compilation works as expected.
This repo doesn't generate any docker layer and it doesn't make any dispatch either.

gsKit
This repo uses the docker image ps2dev/ps2sdk:latest as reference for the CI/CD process. The CI/CD in this case just check that the compilation works as expected.

This repo generate:
3rd docker layer, named ps2dev/gsKit:latest and it is composed by:
alpine:latest + ps2toolchain + ps2sdk + gsKit
Once that the docker image has been build and uploaded to DockerHub, a dispatch action is being sent to ps2sdk-ports repo.

ps2sdk-ports
This repo uses the docker image ps2dev/gsKit:latest as reference for the CI/CD process. The CI/CD in this case just checks that the compilation works as expected.
This repo generate:
4th docker layer, named ps2dev/ps2sdk-ports:latest and it is composed by:
alpine:latest + ps2toolchain + ps2sdk + gsKit + ps2sdk-ports
Once that the docker image has been build and uploaded to DockerHub, a dispatch action is being sent to ps2dev repo.

ps2dev
This is a new repo created with the main purpose of an offer to developers the whole PS2 environment. This is the REPO that you MUST clone if you want to prepare your machine for the ps2 development.
This repo uses the docker image ps2dev/ps2sdk-port:latest as reference for the CI/CD process.
This repo generate:
5th docker layer, named ps2dev/ps2dev:latest and it is composed by:
alpine:latest + ps2toolchain + ps2sdk + gsKit + ps2sdk-ports + ps2-packer + ps2client
A precompiled toolchain for Ubuntu x64 and MacOS x64, where lazy devs can just go there and download the zip file. It is composed by:
ps2toolchain + ps2sdk + gsKit + ps2sdk-ports + ps2-packer + ps2client
```

**Comment by carstene1ns** [comment]
The overall approach looks good to me.
However, we need to make sure this integrates well with our planned changes (pacman for building and distributing libraries).

I already had the idea to split the toolchain repo as well, so :+1: from me.

**Comment by fjtrujy** [comment]
> The overall approach looks good to me.
> However, we need to make sure this integrates well with our planned changes (pacman for building and distributing libraries).
> 
> I already had the idea to split the toolchain repo as well, so 👍 from me.

Hello,
This is totally fine, you can dispatch notifications to other repositories to trigger their CI/CD.

I don't know if you wanna discuss the implementation details here or in a different place.

**Comment by wally4000** [comment]
Great idea. I was looking at getting the windows toolchain working via CI with the help of the fantastic DarkFlea.

Perhaps we could work together on this, we're all on the PSP Homebrew Discord in #psp-toolchain if you wish to join https://discord.gg/bePrj9W
