### ISSUE TITLE
Docker image can't be built as Ubuntu 17.10 is EOL 

### ISSUE THREAD

**Issue by NikolausC** [pspdev/pspdev-docker#2]
Changing the ubuntu tag to 18.04 allows the image to be built

**Comment by NikolausC** [comment]
#3 resolves this

**Comment by Scorpeg** [comment]
Or you can add something like 
`sed -i -e 's/archive.ubuntu.com\|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list && \`

 in RUN section, if there is some legacy code, which compiles only on artful.
